config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "search", to: "users#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # フォロー機能
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  
  # バリデーション実装
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  
  def get_profile_image(w, h)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [w, h]).processed
  end
  
  # ユーザーにフォローされているか否かを判定するメソッド
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    #投稿数グラフ出力　gem groupdateをインストールしないと下記の記述は使用不可
    @books_count = Book.group_by_day_of_week(:created_at).size
    #投稿数グラフ出力　gem groupdateをインストールしないと下記の記述は使用不可
    @book_today = Book.where(created_at: Date.today.all_day).count
  end

  def index
    # @user = User.find(params[:id])
    @users = User.all
    @book = Book.new
    @users2 = User.where.not(id: current_user.id)#カレントユーザー以外のidをとってくる
  end
  
  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user =User.find(params[:id])
    @users = user.followers
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search
    user_books = User.find(params[:user_id]).books #user_idで取得したユーザの本の一覧を取得
    created_time = params[:created_at] #created_atをcreated_timeに代入
    if created_time == "" 
      @search_book = "日付が選択されていません"
    else
      @search_book = user_books.where(created_at: created_time.to_date.all_day).count 
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_search.html.erb
<!--投稿本数を日付で検索-->
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th class="table-active">投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <%#= image_tag user.get_profile_image, size: '80x80' %>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= link_to user.followings.count, followings_user_path(user) %></td>
        <td>フォロワー数:<%= link_to user.followers.count, followers_user_path(user) %></td>
        <td>
          <% if user == current_user %>
          <% else %>
            <% if user.is_followed_by?(current_user) %>
              <%=link_to user_relationships_path(user), method: :delete do %>
                <button type="button" class="btn btn btn-danger">フォロー外す</button>
              <% end %>
            <% else %>
              <%=link_to user_relationships_path(user), method: :post do %>
                <button type="button" class="btn btn btn-primary">フォローする</button>
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100, 100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user.followings.count, followings_user_path(user) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
</table>

<% if user == current_user %>
  <div class='row'>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% else %>
    <% if user.is_followed_by?(current_user) %>
      <%=link_to user_relationships_path(user), method: :delete do %>
        <button type="button" class="btn btn btn-danger">フォロー外す</button>
      <% end %>
    <% else %>
      <%=link_to user_relationships_path(user), method: :post do %>
        <button type="button" class="btn btn btn-primary">フォローする</button>
      <% end %>
    <% end %>
<% end %>

app/views/users/_search.html.erb
<!--投稿本数を日付で検索-->
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th class="table-active">投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %><!--titleからnameに変更-->
        <%= f.text_field :name, class: "form-control name" %><!--titleからnameに変更-->
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<!--フォロワー一覧-->
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <h2>Follower Users</h2>
    <table class='table'>
      
      <tbody>
        <% if @users.empty? %>
         <td>ユーザーはいません</td>

        <% else%>
            <% @users.each do |user| %>
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
              <tr>
                <td><%= image_tag user.get_profile_image(50,50) %></td>
                <td><%= user.name %></td>
                <td>フォロー数:<%= link_to user.followings.count, followings_user_path(user) %></td>
                <td>フォロワー数:<%= link_to user.followers.count, followers_user_path(user) %></td>
                <td><%= link_to 'Show', user %></td>
              </tr>
        
            <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/followings.html.erb
<!--フォロイー一覧-->
<div class='container px-5 px-sm-0'>
  <div class='row'>

    <h2>Follow Users</h2>
    <table class='table'>
      
      <tbody>
        <% if @users.empty? %>
         <td>ユーザーはいません</td>

        <% else%>
            <% @users.each do |user| %>
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
              <tr>
                <td><%= image_tag user.get_profile_image(50,50) %></td>
                <td><%= user.name %></td>
                <td>フォロー数:<%= link_to user.followings.count, followings_user_path(user) %></td>
                <td>フォロワー数:<%= link_to user.followers.count, followers_user_path(user) %></td>
                <td><%= link_to 'Show', user %></td>
              </tr>
        
            <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      
        <h2>User info</h2>
        <%= render 'info', user: current_user %>

        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
      <div class='col-md-8 offset-md-1'>
        <%= render 'books/search', user: @user %>
        <h2>Users</h2>
        <%= render 'index',users: @users %>
      </div>

  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books, user: @user %>

    <!--投稿数の前日比・前週比-->
        <!--前日比-->
        <table class="table table-bordered">
          <thead>
            <tr>
              <td colspan="1" class="table-active">今日の投稿数</td>
              <td colspan="1" class="table-active">前日の投稿数</td>
              <td colspan="1" class="table-active">前日比</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
              <td><%= @yesterday_book.count %></td>
              <td style="width: 40%"><!--このセルの横幅を40%に指定-->
               <% if @yesterday_book.count == 0 %>
                前日の投稿が0のため計算できません
               <% else %>
               　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
               　<%= (@the_day_before * 100).round %>
               <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <!--前週比-->
        <table class="table table-bordered">
          <thead>
            <tr>
              <td colspan="1" class="table-active">今週の投稿数</td>
              <td colspan="1" class="table-active">前週の投稿数</td>
              <td colspan="1" class="table-active">前週比</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
              <td><%= @last_week_book.count %></td>
              <td style="width: 40%">
              <% if @last_week_book.count == 0 %>
              前週の投稿が0のため計算できません
              <% else %>
                <% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f %>
                <%= (@the_week_before * 100).round %>%
              <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <!--過去七日間の投稿表-->
        <table class="table table-bordered">
         <thead>
          <tr>
           <th colspan="1" class="table-active">６日前</th>
           <th colspan="1" class="table-active">5日前</th>
           <th colspan="1" class="table-active">4日前</th>
           <th colspan="1" class="table-active">3日前</th>
           <th colspan="1" class="table-active">２日前</th>
           <th colspan="1" class="table-active">昨日</th>
           <th colspan="1" class="table-active">今日</th>
          </tr>
         </thead>
         <tbody>
          <tr>
           <td style="width: 14%"><%= @books.created_6days.count %></td>
           <td style="width: 14%"><%= @books.created_5days.count %></td>
           <td style="width: 14%"><%= @books.created_4days.count %></td>
           <td style="width: 14%"><%= @books.created_3days.count %></td>
           <td style="width: 14%"><%= @books.created_2days.count %></td>
           <td style="width: 14%"><%= @yesterday_book.count %></td>
           <td style="width: 14%"><%= @today_book.count %></td>
          </tr>
         </tbody>
        </table>
        <canvas id="myLineChart"></canvas><!--chart.jsはグラフ描画エリアの指定に、canvas要素を使用-->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script><!--Chart.jsを使用するために、CDNに公開されているjsファイルを読み込み-->
          <script>
            $(document).on('turbolinks:load', function() {
              var ctx = document.getElementById("myLineChart");
              var myLineChart = new Chart(ctx, {
                type: 'line',//描画するグラフを指定。今回は折れ線グラフ
                data: {
                  labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                  datasets: [
                    {
                      label: '投稿した本の数',
                      data: [
                        <%= @books.created_6days.count %>,
                        <%= @books.created_5days.count %>, 
                        <%= @books.created_4days.count %>, 
                        <%= @books.created_3days.count %>, 
                        <%= @books.created_2days.count %>, 
                        <%= @yesterday_book.count %>, 
                        <%= @today_book.count %>
                      ],
                      borderColor: "rgba(0,0,255,1)",
                      backgroundColor: "rgba(0,0,0,0)",
                      tension: 0.4
                    }
                  ],
                },
                options: {
                  title: {
                    display: true,
                    text: '7日間の投稿数の比較'
                  },
                  responsive: true,
                  scales: {
                    y:{
                      suggestedMin: 0,
                      suggestedMax: 10
                    },
                    x:{
                      stacked: true
                    },
                  },
                }
              });
            });
          </script>
          <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
            <%= f.date_field :created_at %><!--年/月/日が表示-->
            <%= f.submit '検索', class: 'btn btn-outline-primary' %>
          <% end %>
          
          <div id="search_result"><!--jsファイルを呼び出し-->
            <% if @search_book.present? %>
              <%= render 'search', search_book: @search_book %><!--検索結果の部分テンプレ呼び出し-->
            <% end %>
          </div>
    </div>
    </div>
  </div>
</div>