config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
    get "search", to: "users#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true,length:{ maximum: 200 }
  
  # scope :スコープの名前, -> { 条件式 }
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
  scope :created_2days, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }#今週 
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }#前週
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @post_comment = PostComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    user_id = Book.find(params[:id]).user.id
    unless user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<!--投稿フォーム-->
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book' , class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%#= image_tag book.user.get_profile_image(80,80) %>
          <%= image_tag book.user.get_profile_image(50,50) %><!--投稿したユーザーと紐づくアイコン-->
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>

          <!--いいね機能-->
        <td class="fav_<%= book.id %>">
          <%= render 'favorites/fav', book: book %>
        </td>
        
        <td>コメント数：<%= book.post_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search.html.erb
<% if user_signed_in? %>
    <div class="search_form">
        <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.text_field :word %>
            <%= f.select :range, options_for_select([['User'], ['Book']]) %>
            <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
            <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>
    </div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%#= render 'form', book: @book %>
  		<%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book' , class: "btn btn-success" %>
        </div>
      <% end %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  	</div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render 'search', user: @user %>
      <h2>Books</h2>
      
      <%= render 'index', books: @books, book: @book, user: @user %>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %><!--空のモデルを渡すため@bookから@newbookに変更-->
    </div>
    <div class='col-md-8 offset-md-1'>
      <!--showページの右側-->
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(50,50) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td class="fav_<%= @book.id %>"><!--いいね機能-->
            <%= render 'favorites/fav', books: @books, book: @book %>
          </td>
          <td><!--コメント件数-->
            コメント数：<span id="comment_count"><%= @book.post_comments.count %></span>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
          <% end %>
          <% if @book.user == current_user %>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <!--コメント一覧-->
      <div id="post-comments">
        <%= render 'post_comments/comment', book: @book %>
      </div>
      <!--コメント機能-->
      <div id="comment-form">
        <%= render 'post_comments/form', book: @book, post_comment: @post_comment %>
      </div>
    </div>
  </div>
</div>